### ISSUE TITLE
ΑΥΤΗ Η ΛΙΣΤΑ ΜΕ ΒΟΗΘΗΣΕ ΠΑΡΑ ΠΟΛΥ!!!!

### ISSUE THREAD

**Issue by PacoPacorius** [sotirismorf/camping-list#1]
ΣΕ ΕΥΧΑΡΙΣΤΩ ΣΩΤΗΡΗ, ΣΩΤΗΡΑ ΤΩΝ ΚΑΛΟΚΑΙΡΙΝΩΝ ΜΟΥ ΔΙΑΚΟΠΩΝ, ΑΔΕΡΦΕ ΜΟΥΥ ΣΕ ΣΥΓΧΑΙΡΩ@!!!! ΘΑ ΞΕΧΝΑΓΑ ΤΟΝ ΦΑΚΟ ΜΟΥ ΚΑΙ ΜΕΤΑ ΠΑΠΑΛΑ ΦΩΣ!!!!!! ΔΕΝ ΘΑ ΒΛΕΠΑΜΕ ΟΥΤΕ ΤΗ ΜΥΤΗ ΜΑΣ!!!!!!!! ΧΑΧΑ ΚΑΛΟ ΕΕΕΕ, ΤΟ ΠΡΟΤΕΙΝΩ ΣΕ ΟΣΟΥΣ ΕΙΝΑΙ ΧΑΖΟΒΙΟΛΗΔΕΣ ΚΑΙ ΞΕΧΝΑΝΕ ΕΥΚΟΛΑ ΣΑΝ ΕΜΕΝΑ!!!!!!!!!!!!!!!

**Comment by sotirismorf** [comment]
ΠΑΡΑΚΑΛΩ ΣΥΝΑΔΕΛΦΕ... ΕΓΩ ΑΝΤΙ ΝΑ ΞΕΧΑΣΩ ΝΑ ΤΟΝ ΦΑΚΟ ΜΟΥ... ΞΕΧΑΣΑ ΝΑ ΠΑΩ ΣΤΟ ΚΑΜΠΙΝΓΚ😵. ΕΠΡΕΠΕ ΝΑ ΤΟ ΓΡΑΨΩ ΚΑΙ ΑΥΤΟ ΜΑΛΛΟΝ🤣😂🤣😂😂🤣😂🤣😂🤣😂😆😆😆😆

**Comment by PacoPacorius** [comment]
XAXAXAXAXAXA ΑΧ ΒΡΕ ΧΩΡΑΤΑΤΖΗ ΠΩΣ ΤΑ ΠΕΤΑΣ ΕΤΣΙ ΑΒΙΑΣΤΑ ΤΑ ΚΑΛΑΜΠΟΥΡΙΑ!!!!!![](https://github.githubassets.com/images/icons/emoji/unicode/1f923.png)
